### PR TITLE
feat: intro

### PR DESCRIPTION
**Pull request by punchanabu**
### Type of Change

- [x] New features
- [ ] Bug fixes
- [ ] Breaking changes
- [ ] Refactor
- [ ] Documentation updates
- [ ] Other (please specify):

## Description
-  add intro page
-  adjust border component a little bit

## Screenshots or GIFs (if applicable)

https://github.com/user-attachments/assets/39bf256a-af8a-4725-b7f5-f674504849f7

### CODE REVIEW

**Comment by punchanabu** [comment]
Oh แบบ route ผิด

**Comment by punchanabu** [comment]
อันนี้คือ `rebase` นะอย่าพึ่งตกใจ 555
Screenshot 2567-10-23 at 16 09 40

**Comment by punchanabu** [comment]
https://github.com/user-attachments/assets/b61523e8-2847-48cd-8533-fc25fe8fff44

**Comment by punchanabu** [comment]
https://github.com/user-attachments/assets/5b7fcc91-c7be-4d3b-8861-fb7bf7cb5367

**Review by ChanatpakornS — COMMENTED** [review]
LGTM! but add the  fade up text pls

**Review by TeeGoood — APPROVED** [review]
LGTM!!!

**Pull request merged**
